apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: flask_blog:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5009
---
apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
spec:
  selector:
    app: flask-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5009
  type: ClusterIP